export { default as Button } from './Button'
export { default as Header } from './Header'
export { default as Section } from './Section'
export { default as Hero } from './Hero'
export { default as Discover } from './Discover'
export { default as Theater } from './Theater'
export { default as News } from './News'